### ISSUE TITLE
Gigantic image on homepage

### ISSUE THREAD

**Issue by valentinilas** [tagion/tagion-home#287]
Noticed this image is 15MB:
https://tagion.org/static/forest-21f9fb6472d7112eb42ecbc7eb9d989c.png

Consider scaling and compressing

**Comment by Kristian-Tagion** [comment]
Compressed down to 520 KB JPG. Perhaps too hard?

**Comment by Kristian-Tagion** [comment]
Image put on diet. Thanks for the feedback. Closing for now (image was first put on a diet down to 4.5 MB a while back, and now down to 520 KB).
